CREATE DATABASE HEROIS_SOLIDARIOS;
USE HEROIS_SOLIDARIOS;

CREATE TABLE CONTATE_NOS(
    COD_CONTATO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    ASSUNTO VARCHAR(20),
    MENSAGEM VARCHAR(256)
);

CREATE TABLE VISITAS(
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_VIS DATE,
    HORARIO_VISITA TIME,
    LOCAL VARCHAR(40),
    HISTORIA VARCHAR(100),
    ENDERECO VARCHAR(100)
);

CREATE TABLE FOTO (
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    FOTO BLOB,
    LEGENDA VARCHAR(50) ,
    COD_VIS_GALERIA INT,
    FOREIGN KEY (COD_VIS_GALERIA) REFERENCES VISITAS(CODIGO)
);

CREATE TABLE USUARIO(
    CODIGO INT AUTO_INCREMENT,
    ADMINISTRADOR TINYINT(1) NOT NULL,
    NOMECOMPLETO VARCHAR (80),
    EMAIL VARCHAR (100),
    LOGIN_USUARIO VARCHAR(32) NOT NULL,
    SENHA_USUARIO VARCHAR(32) NOT NULL,
    CPF VARCHAR(14),
    ENDERECO TEXT(100),
    DATALOGIN DATETIME,
    PRIMARY KEY (CODIGO)
);

CREATE TABLE DOACAO_DIN(
    CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    QUANTIA DECIMAL (10,2),
    DESCRICAO VARCHAR(100),
    COD_USUARIO INT,
    FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(CODIGO)
);

CREATE TABLE DOACAO_ITENS(
    QUANTIDADE INT (2),
    TIPO_DOACAO VARCHAR(30),
    INFORMACAO_DOACAO VARCHAR(30),
    OUTROS_ITENS VARCHAR(30),
    COD_DOACAO_ITENS INT AUTO_INCREMENT PRIMARY KEY,
    COD_USUARIO INT,
    FOREIGN KEY (COD_USUARIO ) REFERENCES USUARIO (CODIGO)
);

CREATE TABLE TEMP_USU(
	COD_USUARIO INT,
	COD_VISITA INT,
	FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO(CODIGO),
	FOREIGN KEY (COD_VISITA) REFERENCES VISITAS(CODIGO),
	PRIMARY KEY (COD_USUARIO, COD_VISITA)

);


INSERT INTO CONTATE_NOS (NOME, EMAIL, ASSUNTO, MENSAGEM) VALUES ('MATHEUS','MATHEUS123@GMAIL.COM','QUERO DOAR','NÃO CONSIGO DOAR'),
('MARIA','MARIA12@GMAIL.COM','QUERO DOAR DINHEIRO','NÃO CONSIGO DOAR DINHEIRO'),
('LUCIA','LUCIA@GMAIL.COM','DINHEIRO','EFETUAR PAGAMENTO'),
('PEDRO','PEDRO@GMAIL.COM','DOAR','BRINQUEDO'),
('CAROLINE','CAROLINE1@GMAIL.COM','OBJETOS','NÃO CONSIGO DOAR');

select * FROM CONTATE_NOS;
INSERT INTO VISITAS (DATA_VIS, HORARIO_VISITA, LOCAL, HISTORIA, ENDERECO) VALUES ('2017-02-05', '13:42:31', 'HOSPITAL PRAZERES', 'AQUI FOI FUNDADO O HOSPITAL', 'RUA CHILE n40'),
('2017-07-08', '15:22:11', 'HOSPITAL PRAZERES','AQUI FOI ONDE SE REUNIU', 'RUA CHILE n40'),
('2017-04-15', '10:52:51', 'HOSPITAL PRAZERES', 'FOI FEITO PARA PESSOAS', 'RUA CHILE n40'),
('2017-08-04', '14:20:45', 'HOSPITAL GUARARAPES','AQUI É UM HOSPITAL', 'RUA CASTANHARI n52'),
('2017-02-05', '13:00:12', 'HOSPITAL MORENO', 'VOCÊ PODE FAZER VISITAS', 'RUA MARECHAL  n54');

INSERT INTO FOTO (LEGENDA) VALUES ('FOTO DO PAULO'),
('FOTo feita no hospital prazeres'),
('HOSPITAL GUARARAPES'),
('FOTO COM OS HEROIS'),
('AJUDANDO CRIANÇAS');


INSERT INTO USUARIO (NOMECOMPLETO, EMAIL, LOGIN_USUARIO, SENHA_USUARIO, CPF, ENDERECO, DATALOGIN) VALUES ('MARIANA SILVA DE PAULA', 'MARIANA@GMAIL.COM', 'MARIANA123','123456','456720475', 'RUA FULANO', '2017-05-04 13:12:02'),
('PAULO ANDRADE MARTINS', 'PAULO@GMAIL.COM', 'PAULO123','123456','12720475', 'RUA CASCATA', '2017-02-14 15:45:32'),
('JULIA MARIA DO CARMO', 'JULIA@GMAIL.COM', 'JULIA123','123456','75484655', 'RUA GUARARAPES', '2017-05-17 16:32:01'),
('RUTE SIQUEIRA DA SILVA', 'RUTE@GMAIL.COM', 'RUTE123','123456','98657475', 'RUA CHILE ', '2017-07-12 13:15:21'),
('LUCIA DA SILVA RODRIGUES', 'LUCIA@GMAIL.COM', 'LUCIA123','123456','865795463', 'RUA ARGENTINA', '2017-01-27 14:54:02');


INSERT INTO DOACAO_DIN (QUANTIA, DESCRICAO) VALUES (123.02, 'VALOR PARA DOAR'),
(250.00, 'DOAR DINHEIRO'),
(270.50, 'DOAR DINHEIRO'),
(300.10, 'DOAR DINHEIRO'),
(150.00, 'DOAR DINHEIRO');

INSERT INTO DOACAO_ITENS (QUANTIDADE, TIPO_DOACAO, INFORMACAO_DOACAO, OUTROS_ITENS) VALUES (2, 'BRINQUEDO', 'DOAR BRINQUEDOS', 'null'),
(8, 'ROUPAS', 'QUERO DOAR ROUPAS', 'null'),
(5, 'ROUPAS', 'QUERO DOAR ROUPAS', 'null'),
(5, 'BRINQUEDOS', 'QUERO DOAR BRINQUEDOS', 'null'),
(7, 'ROUPAS', 'QUERO DOAR ROUPAS', 'null');
