CREATE DATABASE HEROIS_SOLIDARIOS;
USE HEROIS_SOLIDARIOS;

CREATE TABLE CONTATE_NOS(
    COD_CONTATO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    EMAIL VARCHAR(50),
    ASSUNTO VARCHAR(20),
    MENSAGEM VARCHAR(256)
);

CREATE TABLE VISITAS(
    COD_VISITA INT AUTO_INCREMENT PRIMARY KEY,
    DT_VISITA DATE,
    LOCAL_VISITA VARCHAR(40),
    ENDEREÇO VARCHAR(100)
);

CREATE TABLE GALERIA_FOTOS (
    COD_GF INT AUTO_INCREMENT PRIMARY KEY,
    LOCAL_FT VARCHAR (40),
    FOTOS BLOB,
    HISTÓRIA VARCHAR(200)
);

CREATE TABLE USUARIO(
    COD_USUARIO INT AUTO_INCREMENT,
    LOGIN_USUARIO VARCHAR(32),
    NOMECOMPLETO VARCHAR (80),
    CPF VARCHAR(14),
    ENDERECO TEXT(200),
    EMAIL VARCHAR (200),
    SENHA_USUARIO VARCHAR(32),
    PRIMARY KEY (COD_USUARIO)
);

CREATE TABLE DOACAO_DIN(
    QUANTIA VARCHAR(20),
    NOME_DOADOR VARCHAR(80),
    DESCRICAO VARCHAR(100),
    COD_DOACAO_DIN INT,
    COD_DOACAO INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (COD_DOACAO_DIN) REFERENCES USUARIO(COD_USUARIO)
);


CREATE TABLE DOACAO_ITENS(
    QUANTIDADE INT (2),
    TIPO_DOACAO VARCHAR(30),
    INFORMACAO_DOACAO VARCHAR(30),
    OUTROS_ITENS VARCHAR(30),
    COD_DOACAO_ITENS INT,
    COD_DOACAO INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (COD_DOACAO_ITENS) REFERENCES USUARIO (COD_USUARIO)
);

CREATE TABLE DOACAO_TEMPO(
	LOCAL_VISITA VARCHAR(50),
    DIA_VISITA DATE,
    HORARIO_VISITA TIME,
    COD_DOACAO_TEMPO INT,
    COD_DOACAO INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (COD_DOACAO_TEMPO) REFERENCES USUARIO (COD_USUARIO)
    
);

drop database HEROIS_SOLIDARIOS;
